---
units: units.tsv
sample: samples.tsv

# files and directories
working_dir: "temp/"
result_dir: "results/"


#Parameters for the rules

GENOME_ZIP_GTF_URL: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/gencode.vM20.annotation.gtf.gz
#ENCODE repeat_masker
REPEAT_GTF_URL: http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCm38_Ensembl_rmsk_TE.gtf.gz

#STAR


#TE_Transcript
